apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quotes-ing
spec:
  ingressClassName: nginx
  rules:
    - host: quotes.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quotes-svc
                port:
                  number: 80
