apiVersion: v1
kind: Service
metadata:
  name: quotes-svc
spec:
  type: ClusterIP
  selector:
    app: quotes-api
  ports:
    - port: 80          # porta exposta pelo service
      targetPort: 8000  # porta do container
      protocol: TCP
